[package]
name = "issues"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "GPL-3.0-or-later"

[lib]
test = false

[dependencies]
librad = { path = "../radicle-link/librad" }
argh = "0.1"
anyhow = "1"
radicle-keystore = "0"
serde_json = "1.0"
automerge = { path = "../../automerge-stuff/automerge-rs/automerge" }
tracing-subscriber = "0.2"
lazy_static = "1.4"

[dependencies.serde]
version = "1.0"
features = ["derive"]
